### ISSUE TITLE
onChange called multiple times

### ISSUE THREAD

**Issue by ghost** [dnasir/jquery-cascading-dropdown#28]
If I have a group of dependent selects, and changing the value of one group member, causes the others to reload, then a global `onChange` handler will be called several times. Here's a demo:

http://jsfiddle.net/Qxaa9/5/

In general, I don't think this is the behaviour most people would want, and it would seem much more useful if the handler was only called once after all the selects in the group have been reloaded.

**Comment by dnasir** [comment]
Note to self: look into JS debounce.

**Comment by dnasir** [comment]
I think this should be handled by the application code. Something as simple as using `setTimeout` should work. Technically, whenever a child dropdown raises an `onChange` event, it makes sense for the group instance to raise the same event.
