### ISSUE TITLE
Checkbox with Multiple select?

### ISSUE THREAD

**Issue by vlasvlasvlas** [dnasir/jquery-cascading-dropdown#34]
hi! this cascading dropdown its great!!

can we have the alternative of checkbox for the Multiple select example? that would be very nice!

i mean using this kind of Multiple select usability: 

http://silviomoreto.github.io/bootstrap-select/3/
(ctrl+f search for "And with multiple selects:")

```
 <select class="selectpicker" multiple>
      <option>Mustard</option>
      <option>Ketchup</option>
      <option>Relish</option>
  </select>
```

**Comment by dnasir** [comment]
Added in commit 47359f20cf79a4e8066a28e77996dc0bbbd1f5bd

**Comment by vlasvlasvlas** [comment]
txs!
