### ISSUE TITLE
Items in dropdown sorting by value not label

### ISSUE THREAD

**Issue by DaveBowman** [dnasir/jquery-cascading-dropdown#36]
I love this plugin, but I can't figure out how to sort the items in the dropdown by the 'label' rather than the 'value'. For example, here's my JSON array:

{"2":"A","1":"B"}

But then here's my dropdown: 

![image](https://cloud.githubusercontent.com/assets/6858156/4534272/d1dbbdb8-4da3-11e4-9f6a-eb89e3f1a8d8.png)

I don't know that this is a bug; likely more of a usability issue. I'm pulling data from a SQL backend to create the JSON array, and the IDs are definitely not in the order I want it to display to the end-user. Is changing the script to sort by label an easy change/tweak?

Thank you in advance. -Dave

**Comment by dnasir** [comment]
I'm going to close this due to inactivity.
