### ISSUE TITLE
Force update eventhandler

### ISSUE THREAD

**Issue by VisualBean** [dnasir/jquery-cascading-dropdown#43]
Is there a handle to force an update of a selectbox?
My problem is that i have a checkbox that i'm using in the ajax call to the source of a selectbox.

I want the "final" selectbox to update when i click the checkbox, so i don't have to reselect a value

**Comment by VisualBean** [comment]
Fixed - looked throug hthe code and found the function
 $('.mydropdown').cascadingDropdown('update');

**Comment by spacejay** [comment]
How do you utilize the update function?

**Comment by VisualBean** [comment]
try calling $('.mydropdown').cascadingDropdown('update'); from your js - det dropdowns will refresh.
