### ISSUE TITLE
Update source on change

### ISSUE THREAD

**Issue by spacejay** [dnasir/jquery-cascading-dropdown#44]
How do I trigger a reload of the dropdown source on a change? The first dropdown in my cascading dropdown is a multiple select containing a list of football teams. When a team is selected I would like the source/select options to update so only the selected team and teams who have played against "selected" team are displayed.

**Comment by dnasir** [comment]
@spacejay Can you share your code? Do you wish to reload the items in the first dropdown when an item is selected?

**Comment by spacejay** [comment]
Yes, exactly! As a sort of workaround I have moved the selection of team to step3, so I share step 3 here. I would still like to reload the dropdown when an item is selected though.

    selector: '.step3',
    requires: ['.step1', '.step2'],
    requireAll: true,
    source: function (request, response) {
        $.getJSON('getParticipant.php', request, function (data) {
            var selectOnlyOption = data.length <= 1;
            response($.map(data, function (item, value) {
                return {
                    label: item,
                    value: value,
                    selected: selectOnlyOption
                };
            }));
        });
    }

**Comment by dnasir** [comment]
Closing this for now. If you need me to do something about this, please reopen it in the future.
