### ISSUE TITLE
Drop down not populating using URL pointing to the web service that provides the dropdown items

### ISSUE THREAD

**Issue by teejayphp** [dnasir/jquery-cascading-dropdown#45]
The following code for selector: '.DEPT_ID' with source: 'FilterActions.php?action=lstdept'

<div class="filtering" style="width: 100%;"></div>

```
<form>
    <script type="text/javascript">
        $('#filtering').cascadingDropdown({
        textKey: 'label',
        valueKey: 'value',
        selectBoxes: [
        {
        selector: '.DEPT_ID',
        //paramName: 'DEPT_ID',
        //usePost: true,
        //useJson: true,
        source: 'FilterActions.php?action=lstdept'
        }
    ]
    });
    </script>
    <button type="submit" id="LoadRecordsButton">Load records</button>
</form>
```

returns the JSON object 
[{"label":"Administration","value":"10"},{"label":"Marketing","value":"20"},{"label":"Purchasing","value":"30"},{"label":"Human Resources","value":"40"},{"label":"Shipping","value":"50"},{"label":"IT","value":"60"},{"label":"Public Relations","value":"70"},{"label":"Sales","value":"80"},{"label":"Executive","value":"90"},{"label":"Finance","value":"100"},{"label":"Accounting","value":"110"},{"label":"Treasury","value":"120"},{"label":"Corporate Tax","value":"130"},{"label":"Control And Credit","value":"140"},{"label":"Shareholder Services","value":"150"},{"label":"Benefits","value":"160"},{"label":"Manufacturing","value":"170"},{"label":"Construction","value":"180"},{"label":"Contracting","value":"190"},{"label":"Operations","value":"200"},{"label":"IT Support","value":"210"},{"label":"NOC","value":"220"},{"label":"IT Helpdesk","value":"230"},{"label":"Government Sales","value":"240"},{"label":"Retail Sales","value":"250"},{"label":"Recruiting","value":"260"},{"label":"Payroll","value":"270"},{"label":"tst","value":"280"}]

This is in line with the Example JSON object

```
[
    {
        "label": "Item 1",
        "value": "1"
    },
    {
        "label": "Item 2",
        "value": "2"
    }
]
```

The drop down is not coming up. What is the issue and what is the solution.

The php code returning the JSON object is as follows

```
//Getting records (listAction)
if($_GET["action"] == "lstdept")
{
    $sql = "SELECT DEPARTMENT_ID, DEPARTMENT_NAME FROM departments";
    $result = db_do_query($conn, $sql);

    //Add all records to an array
    $rows = array();
    $stid = oci_parse ($conn, $sql);
    oci_execute($stid);
    while($row=oci_fetch_array($stid, OCI_BOTH))
    {
        $element = array();
        $element["label"]= $row['DEPARTMENT_NAME'];
        $element["value"]= $row['DEPARTMENT_ID'];
        $rows[] = $element;
    }

    //Return result to Form
    $cFilterResult = array();
    $cFilterResult=$rows;
    print json_encode($cFilterResult);
}
```

**Comment by dnasir** [comment]
@teejayphp 
Hi,
Firstly, the textKey and valueKey are no longer required. The plugin will always expect you to provide the items using the label/value format. Secondly, is the HTML markup an extract of the rest of the code, or is that it? I don't see the select box that you're referencing in the init code. You need something like this for this to work:

```html
<form id="filtering">
  <select class="DEPT_ID"></select>
  <button type="submit" id="LoadRecordsButton">Load records</button>
</form>
```

The plugin doesn't generate the markup for the select box, just the contents.

**Comment by teejayphp** [comment]
Hi Nasir,

Thank you for the tip 'The plugin doesn't generate the markup for the select box, just the contents.'
After revising the code as below
<div class="filtering">
    <form>
	    <fieldset id="filter">
		    <div title="Department">
			    <label>Department: <select class="select1" id="select1" name="select1">
					<option value="x">All Department</option>
				</select></label>
			</div>
		    <div title="Country">
			    <label>Country: <select class="select2" id="select2" name="select2">
					<option value="x">All Countries</option>
				</select></label>
			</div>
		    <div title="Location">
			    <label>Location: <select class="select3" id="select3" name="select3">
					<option value="x">All Locations</option>
				</select></label>
			</div>
		</fieldset>
    	<script type="text/javascript">
     	$(document).ready(function() {
	    	$('#filter').cascadingDropdown({
	     	selectBoxes: [
	     	{
		     	selector: '.select1',
		     	paramName: 'DEPT_ID',
		     	selected: 0,
		     	//usePost: true,
		     	useJson: true,
		     	source: 'FilterActions.php?action=lstdept'
	     	},
	     	{
		     	selector: '.select2',
		     	paramName: 'CNTRY_ID',
		     	selected: 23,
		     	//usePost: true,
		     	useJson: true,
		     	source: 'FilterActions.php?action=lstcntry'
		    },
	     	{
		     	selector: '.select3',
		     	//requires: ['.select2'],
		     	paramName: 'LOCN_ID',
		     	selected: 0,
		     	usePost: true,
		     	useJson: true,
		     	source: 'FilterActions.php?action=lstlocn&Country=' + $("#select2").children("option:selected").val()
		    }
	     	]
			})
		});
     	</script>
		<button type="submit" id="LoadRecordsButton">Load records</button>
    </form>
</div>

I am able to display Departments, Countries & Locations. I am however not able to get Locations to use the Country Selected source: 'FilterActions.php?action=lstlocn&Country=' + $("#select2").children("option:selected").val().

![cascadedropdown](https://cloud.githubusercontent.com/assets/11176496/7633089/9ce7242a-fa6f-11e4-859b-2653ce3e5776.jpg)

Before attempting to use onChange (eventHandler), I attempted setting selected: 23 for selector: '.select2'. The dropdown is populated correctly but $("#select2").children("option:selected").val() returns the value x set in the HTML.

Please help me with some code / reference on how to use the selected option correctly and how to use onChange (eventHandler) to reflect changes made to selectors select1 and select2.

Thomas Joseph

**Comment by teejayphp** [comment]
Hi Nasir,
Thank you for the tip "The plugin doesn't generate the markup for the
select box, just the contents."
After revising the code as below

<div class="filtering">
    <form>
     <fieldset id="filter">
      <div title="Department">
       <label>Department: <select class="select1" id="select1"
name="select1">
     <option value="x">All Department</option>
    </select></label>
   </div>
      <div title="Country">
       <label>Country: <select class="select2" id="select2" name="select2">
     <option value="x">All Countries</option>
    </select></label>
   </div>
      <div title="Location">
       <label>Location: <select class="select3" id="select3" name="select3">
     <option value="x">All Locations</option>
    </select></label>
   </div>
  </fieldset>
     <script type="text/javascript">
      $(document).ready(function() {
      $('#filter').cascadingDropdown({
       selectBoxes: [
       {
        selector: '.select1',
        paramName: 'DEPT_ID',
        selected: 0,
        //usePost: true,
        useJson: true,
        source: 'FilterActions.php?action=lstdept'
       },
       {
        selector: '.select2',
        paramName: 'CNTRY_ID',
        selected: 23,
        //usePost: true,
        useJson: true,
        source: 'FilterActions.php?action=lstcntry'
      },
       {
        selector: '.select3',
        //requires: ['.select2'],
        paramName: 'LOCN_ID',
        selected: 0,
        usePost: true,
        useJson: true,
        source: 'FilterActions.php?action=lstlocn&Country=' +
$("#select2").children("option:selected").val()
      }
       ]
   })
  });
      </script>
  <button type="submit" id="LoadRecordsButton">Load records</button>
    </form>
</div>

I am able to display Departments, Countries & Locations. I am however not
able to get Locations to use the Country Selected source:
'FilterActions.php?action=lstlocn&Country=' +
$("#select2").children("option:selected").val(). I am attaching the screen
shot for your kind reference.

Before attempting to use onChange (eventHandler), I attempted setting selected:
23 for selector: '.select2'. The dropdown is populated correctly but
$("#select2").children("option:selected").val() returns the value x set in
the HTML.

Please help me with some code / reference on how to use the selected option
correctly and how to use onChange (eventHandler) to reflect changes made to
selectors select1 and select2.

Thomas Joseph



On Wed, May 13, 2015 at 3:46 PM, Dzulqarnain Nasir <notifications@github.com

**Comment by dnasir** [comment]
@teejayphp I'll have a look at your code, but in the meantime I suggest you have a look at the demo. It may help you figure out what you need to do to get your code working.

**Comment by dnasir** [comment]
Housekeeping
