### ISSUE TITLE
select onChange - would like to also get the label.

### ISSUE THREAD

**Issue by VisualBean** [dnasir/jquery-cascading-dropdown#46]
As it is right now, the onChange event provides event, value and requiredValues - I would like to be able to get the label information as well.
Maybe if you return the selectedObject instead of the value? (if at all possible)
Like - 

```
onChange: function(event, selectObject, requiredValues){
alert(selectObject.value);
alert(selectObject.label);
}
```

Please consider adding this :) - thanks

**Comment by dnasir** [comment]
@VisualBean This is good idea. I'll consider adding this, but it will break stuff for the people who already have it implemented this way.

**Comment by dnasir** [comment]
I think this will break many things, so I'm going to add this to the next major release. Maybe 2.0.

**Comment by dnasir** [comment]
Extract the label from the event object like so: `$(event.target).find(':selected').text()`
