### ISSUE TITLE
selected with require

### ISSUE THREAD

**Issue by jeffreychea** [dnasir/jquery-cascading-dropdown#48]
I'm implementing the cascading drop down lists on an asp.net form.

I have 2 drop down lists and another asp.net control.
After making the selections on the drop down lists, I want to do a postback.
I also want the drop down lists to keep it's value.
This can be done using the selected attribute.

When I use selected on the first drop down list, it works.
When I use selected on the second drop down lists, it works.

However, when I set the second drop down list to require the first drop down list, selected stops working after the postback.

**Comment by dnasir** [comment]
@jeffreychea are you populating the second dropdown via ajax by any chance?
