### ISSUE TITLE
Multiple types of controls. 

### ISSUE THREAD

**Issue by frapps** [dnasir/jquery-cascading-dropdown#51]
Hi, have you ever considered trying to support multiple different controls? 

I was starting to think about how to implement this, but not really sure where to start. Do you have any pointers?

Cheers

Daniel

**Comment by dnasir** [comment]
Hi,

It's possible, but I would create a new project for that.

Would you like to collaborate with me on this?

**Comment by frapps** [comment]
Yes I would like to. I am not as proficient in Javascript  as you are. Judging on the plugin. Where can we start?

**Comment by dnasir** [comment]
Upon further consideration, it's simpler to just use something like Knockout or React to handle this kind of scenario.
