### ISSUE TITLE
more dropdown list ?

### ISSUE THREAD

**Issue by cvelele** [dnasir/jquery-cascading-dropdown#59]
I search the web for cascade dropdown list and find this one that almost fits fine. As title says how to add more dropdown list categories (camera resolution, front camera..) and when everything match, a generated list of phones to be a hyperlink (to click on it)?

My knowledge is rather beginners  so please be patient in explaining. Talking about BASIC example.

I add in html:

<select class="step4" name="camera">
<option value="">Camera Resolution</option>
<option value="1">1 M</option>
<option value="2">2 M</option>
<option value="3">3 M</option>
</select>

add in ajax-mocks.js new dropdown list

```
            maker: 'Motorola',
    model: 'Moto X',
    screen: 4.7,
    resolution: 720,
    storage: [16, 32],
    camera: 1
```

but the rest of js is very hard for me to modify. Especially the part to show hyperlink matches.

Need assistance, thanks.

**Comment by dnasir** [comment]
@cvelele You would need to add an additional property to the item for URL. i.e.

    maker: 'Motorola',
    model: 'Moto X',
    screen: 4.7,
    resolution: 720,
    storage: [16, 32],
    camera: 1
    url: 'http://www.somewhere.com'

And then you'll need to implement some sort of logic to find the item you're looking for based on the dropdown values. You'll need to figure this out yourself. Refer to the example code.

To get the URL displayed, you can modify the Knockout template to include the URL in the form of a link:

    <ul data-bind="foreach: phones, visible: phones().length > 0">
        <li>
            <span data-bind="text: maker"></span>
            <span data-bind="text: model"></span>
            <a data-bind="attr: { href: url }">Link</a>
        </li>
    </ul>

**Comment by cvelele** [comment]
URL tips work and now I have hyperlink.

But adding 4th dropdown list it is a complicated for my knowledge. Thanks.

I will try by myself to add showing picture of phone. Hope so. Any tips again?

**Comment by cvelele** [comment]
Hey, a manage to display image next to model and maker adding

maker: 'Motorola',
model: 'Moto X',
screen: 4.7,
resolution: 720,
storage: [16, 32],
camera: 1
url: 'http://www.somewhere.com'
imageSrc: 'http://www.asb.com/picture.jpg'     <------------------------------

and

<ul data-bind="foreach: phones, visible: phones().length > 0">
    <li>
        <span data-bind="text: maker"></span>
        <span data-bind="text: model"></span>
        <a data-bind="attr: { href: url }">Link</a>
        <img data-bind="attr: { src: imageSrc }, style: {width: 100 + 'px', height: 50 + 'px'}" />   <--------
    </li>
</ul>

Lets move on.

What changes do I need to make if I want to display Operating sistem (iOS, Android ...) instead of Screen size or Screen resolution?

**Comment by cvelele** [comment]
I can change number with text in first (basic) and second (dynamic) example in:

<select class="step1" name="screen">
 <option value="" selected="selected">Screen size</option>
 <option value="4">Android</option>
 <option value="4.3">iOS</option>
</select>

and in second

<script type="text/javascript">

selectBoxes: [
{
selector: '.step1',
source: [{ label: 'Android', value: 1 }, { label: 'iOS', value: 2 }]


and work fine. But I need in second droplist text to appear. And when change for second droplist in ajax-mocks.js:

var phoneList = [
maker: 'HTC',
model: 'One S',
screen: 4.3, 
resolution: 'Android', <------- here

getting strange result. Actually the third droplist doesn't filter ''selectOnlyOption''?

It probably have problems because resolution is number and i put text, so what else do i have to change to work ok?
thanks

**Comment by dnasir** [comment]
@cvelele you could simply change the values and the filtering/sorting logic.
