### ISSUE TITLE
useJSON with POST and GET

### ISSUE THREAD

**Issue by olimortimer** [dnasir/jquery-cascading-dropdown#61]
I ran into an issue where I was requesting JSON from the server, but the data being **sent** to the server was also being encoded as JSON, rather than urlencoded. This means you would need to use `file_get_contents('php://input')` rather than `$_POST` at the server side to access the data being sent.

I believe the `useJSON` switch should also determine the `contentType` as JSON or false.

`contentType: self.options.useJson ? 'application/json; charset=utf-8' : false,`

However, setting `useJSON: false`, also alters the format of the data **coming back** from the server, meaning you can't simply pass a URL as the `source`, set `useJSON: true` and `usePost: true`, and expect `cascadingDropdown` to handle the population of the dropdowns, as it expects JSON to be returned by the server - you receive an `Uncaught TypeError: Cannot use 'in' operator to search for 'length' in [...]` error.

To summarise, and assuming the server always responds with valid JSON:

```
source: '/api/CompanyInfo/GetCountries',
usePost: true,
useJson: true,
```

This would populate the dropdowns correctly as it sets `dataType: 'json'`, but it also sets `data: JSON.stringify(request)` so you can't access the data in PHP using `$_POST`, and would need to use `file_get_contents('php://input')`.

```
source: '/api/CompanyInfo/GetCountries',
usePost: true,
useJson: false,
```

This would allow you to use `$_POST` correctly as it sets `data: request`, but `cascadingDropdown` falls over because it also sets `dataType` to `undefined` rather than `json` - `Uncaught TypeError: Cannot use 'in' operator to search for 'length' in [...]`.  In this instance, you would need to be passing a function to `source` to then `JSON.stringify(request)`.

For my scenario, the following would make more sense:

```
data: self.options.useJson ? JSON.stringify(request) : request,
dataType: 'json',
type: self.options.usePost ? 'post' : 'get',
contentType: self.options.useJson ? 'application/json; charset=utf-8' : false,
```

Rather than:

```
data: self.options.useJson ? JSON.stringify(request) : request,
dataType: self.options.useJson ? 'json' : undefined,
type: self.options.usePost ? 'post' : 'get',
contentType: 'application/json; charset=utf-8',
```

But for full customisation, maybe the plugin needs a `useJSONRequest`, `useJSONResponse`?

```
data: self.options.useJSONRequest ? JSON.stringify(request) : request,
dataType: self.options.useJSONResponse ? 'json' : undefined,
type: self.options.usePost ? 'post' : 'get',
contentType: self.options.useJSONRequest ? 'application/json; charset=utf-8' : false,
```

**Comment by dnasir** [comment]
@olimortimer Pretty awesome analysis! It's also possible to pass in a function for ``source`` and manually take care of this. Perhaps that's more suitable for your use case?

**Comment by olimortimer** [comment]
Yes in the end I passed a function to `source` (nearly identical to the one in your example), but it seems a bit of a waste to create a function rather than just passing through the source URL - I still think the JSON request and response might need to be looked at?

**Comment by dnasir** [comment]
I'll put this as something to consider.

**Comment by dnasir** [comment]
Just use `source` for this.
