### ISSUE TITLE
TypeError: invalid 'in' operand obj loading json

### ISSUE THREAD

**Issue by aberbenni** [dnasir/jquery-cascading-dropdown#63]
I receive this error (in Firefox) loading json for the first dropdown, I'm using source:"/path/file.json" sintax:
TypeError: invalid 'in' operand obj
isArraylike() jquery.js:584
.each() jquery.js:359
Dropdown.prototype._renderItems() jquery.cascadingdropdown.js:232
Dropdown.prototype._response/<() jquery.cascadingdropdown.js:193
Dropdown.prototype._initSource/this.source/self.xhr<.success() jquery.cascadingdropdown.js:128
jQuery.Callbacks/fire() jquery.js:3143
jQuery.Callbacks/self.fireWith() jquery.js:3255
done() jquery.js:9309
.send/callback() jquery.js:9713

In Chrome the same error is described as

jquery.js:584 Uncaught TypeError: Cannot use 'in' operator to search for '2914' in [
        {
          "label": "Label",
          "value": "v"
        },
        {
          "label": "Label",
          "value": "v"
        },
        [...]
        {
          "label": "Label",
          "value": "v"
        }
 ]

The file contains valid json.

**Comment by dnasir** [comment]
Can you build a jsFiddle/Plnkr so I can test your code?

**Comment by OldProgramCoder** [comment]
This is also crashing for me.  Unfortunately I am pretty new to the whole web thing and jquery so I don't have a clue on how to make a fiddle.  But I have tracked the error down.  Hopefully this helps.
I am trying to get your example working by taking part of it directly and just massaging it.   I want to fill the first select box dynamically at run time.

 ```
$('#example2').cascadingDropdown({
            selectBoxes: [
                {
                    selector: '.JobGuid',
                    source: function (request, response)
                    {
                        $.getJSON('/Task/JobGuid', request, function (data)   
                        {
                            response($.map(data, function (item) {  <<  ERROR OCCURS HERE.                     
                                return {
                                    label: item.Label,
                                    value: item.Value
                                }
                            }));
                        });
                    }
                },
                {
                    selector: '.TaskNameGuid',
                    requires: ['.JobGuid'],
                    source: function(request, response) {
                        $.getJSON('/Task/TaskName', request, function(data) {
                            var selectOnlyOption = data.length <= 1;
                            response($.map(data, function(item) {
                                return {
                                    label: item + 'p',
                                    value: item,
                                    selected: selectOnlyOption
                                };
                            }));
                        });
                    }
                },    and so on. 
```
The datatable  is created here.

 ```
      // for testing only.  replace with db call.
     public void Load()
        {
            _jobListDataTable.Columns.Add ( "label");
            _jobListDataTable.Columns.Add ( "value" );
            
            _jobListDataTable.Rows.Add ("Item1" ,"1"  ) ;
            _jobListDataTable.Rows.Add ("Item2" ,"2" ) ;
            _jobListDataTable.Rows.Add ("Item3" ,"3"  ) ;
        }
```
This gets converted to a json  
"[
{"label":"Item1","value":"1"},
{"label":"Item2","value":"2"},
{"label":"Item3","value":"3"}
]"

When $.map is called it calls   this function in the jquery-{version}.js file

```
	
map: function( elems, callback, arg ) {
		var length, value,
			i = 0,
			ret = [];
		// Go through the array, translating each of the items to their new values
		if ( isArrayLike( elems ) ) {       <<  BLOWS UP IN THIS FUNCTION CALL
	            length = elems.length;
			for ( ; i < length; i++ ) {
```

and  this is   function IsArray
```
function isArrayLike( obj ) {
	// Support: real iOS 8.2 only (not reproducible in simulator)
	// `in` check used to prevent JIT error (gh-2145)
	// hasOwn isn't used here due to false negatives
	// regarding Nodelist length in IE
	var length = !!obj && "length" in obj && obj.length,  << EXCEPTION OCCURS ON THIS LINE
		type = jQuery.type( obj );

	if ( type === "function" || jQuery.isWindow( obj ) ) {
		return false;
	}
	return type === "array" || length === 0 ||
		typeof length === "number" && length > 0 && ( length - 1 ) in obj;
}
```
The error is **_Invalid operand to 'in': Object expected_**
                                         
I have checked and the jquery-{version}.js contains the same code in both 2.2.4 and 3.1.0 both of which are on my system.
Hope this helps,  let me know if you need anymore information.

BTW, pretty cool solution you have built.  
Thanks,
Colin

**Comment by OldProgramCoder** [comment]
Fixed.  It looks like there were 2 issues.   


1.   $.map and $.each which are similar but different in what they return ( map returns a new array and each returns the original)    are unable to handle the straight json.   Both returned an error from  isArrayLike( elems ) inside jquery.js.  The solution was to run them through JSON.parse  to create an object that will get past isArrayLike()

2. Once I got there I passed the resulting object $.map and it filled the control with "Undefined" instead of the select text.    I switched to $.each and this give me the right text   

Corrected code is 

```
     $.getJSON('/Task/JobGuid', request, function (data)
                        {
                            response($.each(JSON.parse(data), function (item, index)
                            {
                                return {
                                    label: item.Label,
                                    value: item.Value
                                }
                            }));
                        });
```

Thanks for a great plugin.

Colin

**Comment by dnasir** [comment]
@OldProgramCoder please check that the data returned by the server is actually JSON data. The jQuery API documentation states the the ``$.getJSON()`` method will provide a [``PlainObject``](http://api.jquery.com/Types/#PlainObject) type as one of the parameters for the callback method.

**Comment by OldProgramCoder** [comment]
It was json data as far as I know.

```
public JsonResult JobGuid()
{          
     JobViewModel _jobViewModel = new JobViewModel();
     _jobViewModel.Load();
     var JobList = JsonConvert.SerializeObject(_jobViewModel._jobListDataTable);
     JsonResult jr = Json(JobList,JsonRequestBehavior.AllowGet);
     return jr;
}
```
The data coming out of   JsonConvert.SerializeObject(
 is 

[
{"label":"Item1","value":"1"},
{"label":"Item2","value":"2"},
{"label":"Item3","value":"3"}
]

The data coming out of   Json(JobList,JsonRequestBehavior.AllowGet);
is 

[
{"label":"Item1","value":"1"},
{"label":"Item2","value":"2"},
{"label":"Item3","value":"3"}
]
except that in the latter case it is part of a json object.

Passing JobList back causes the exception mentioned above.

**Comment by OldProgramCoder** [comment]
Finally figured this out completely.    I was calling a c# function in a mvc controller to get the data.  The data was being returned as type JsonResult.   In order to do this I was taking a data table and running it through a 2 step process.
```

var _jasonConvert = JsonConvert.SerializeObject(_dataTable);   
JsonResult _jrSubClassList = Json(__jasonConvert ,JsonRequestBehavior.AllowGet);
return _jrSubClassList;
```

This is wrong.  The plug in is looking for a string that looks like a json object, not a json result.

This is the corrected code
 
```
var _jasonConvert = JsonConvert.SerializeObject(_dataTable);   
return _jasonConvert;      // this is a string.. 
```
Thanks for a great plug in.

**Comment by dnasir** [comment]
Glad you got it sorted out. I'll close this issue now.
