### ISSUE TITLE
Implement custom attributes for dropdown elements

### ISSUE THREAD

**Issue by gierg** [dnasir/jquery-cascading-dropdown#65]
Hi, dnasir,

I've been using a plugin that you make right now, but I want to add some additional attributes on select his option. whether this plugin can handle it?

ex:
`<select class="selectpicker">`
  `<option data-content="<span class='label label-success'>Relish</span>">Relish</option>`
`</select>`

**Comment by dnasir** [comment]
@gierg Sorry, but this is not currently supported. But it sounds like a good idea to implement.

**Comment by dnasir** [comment]
I've refactored the code to include a `_renderItem` method that can be customised. You can add additional attributes there.
