### ISSUE TITLE
why dropdown always disable?

### ISSUE THREAD

**Issue by gierg** [dnasir/jquery-cascading-dropdown#66]
I have a dropdown like this.
![image](https://cloud.githubusercontent.com/assets/1788766/21267076/5066d9f6-c3db-11e6-99f1-1672b97b7e2c.png)

and i have console log result like this...

![capture](https://cloud.githubusercontent.com/assets/1788766/21267178/d71241b6-c3db-11e6-9af7-703a8f03995b.PNG)

why dropdown is still disabled?

**Comment by dnasir** [comment]
@gierg Can you show me your initialisation code? A jsFiddle/Codepen/Plunker would help tremendously.

**Comment by gierg** [comment]
hey @dnasir this is [My code](https://jsfiddle.net/mtz9cqh5/)

**Comment by gierg** [comment]
can you help me @dnasir ?

until now, i can't solving my problem.

**Comment by dnasir** [comment]
@gierg Sorry for the late reply. I was on vacation and got swamped in work when I got back =P

Can you make sure the service returns the required values? Can you send me a sample of how the data structure looks like?

A simple way to test whether the plugin is working as intended is to do something like this https://jsfiddle.net/dzul1983/mtz9cqh5/5/ You can see that the dropdown is enabled when a value is selected.

Also check to see if there are any JS errors which may be preventing the application from proceeding further.
