### ISSUE TITLE
Remove  an option row.

### ISSUE THREAD

**Issue by OldProgramCoder** [dnasir/jquery-cascading-dropdown#68]
I need to be able to remove or add an option row as required.

I pre seed a row with 
```
<select name="JobGuid" class="JobGuid   form-control " onchange="JobGuidChanged" id="JobGuid">
    <option value="">Select Job</option>
   </select>
```

Once the user has selected an option I want to remove this so that they can not select an empty option.

I tried 
`$("div#fieldname option[value='']").remove();`
and 
`$("div#fieldname option[label='Select Job']").remove();`

How can I do this?

Thanks,

**Comment by dnasir** [comment]
@OldProgramCoder There's no built in way to remove individual dropdowns. You can, however, update the dropdown list using the built-in API. Hook into the ``onChange`` event and update the dropdown options as necessary.

Alternatively, you can override the ``_renderItems`` internal method and remove [line 207](https://github.com/dnasir/jquery-cascading-dropdown/blob/master/src/jquery.cascadingdropdown.js#L207) to prevent the original dropdown items from being re-added.
