### ISSUE TITLE
Invalid order select

### ISSUE THREAD

**Issue by hugofabricio** [dnasir/jquery-cascading-dropdown#70]
Hello,

I'm returning an answer in alphabetical order, but to popular select, it sorts by value, has anyone ever had it?

Order return api 

`{
  "4848": "\u00c1gua Branca",
  "4849": "Aguiar",
  "4850": "Alagoa Grande",
  "4851": "Alagoa Nova",
  "4852": "Alagoinha",
  "4853": "Alcantil",
  "4854": "Algod\u00e3o de Janda\u00edra",
  "4855": "Alhandra",
  "4856": "Amparo",
  "4857": "Aparecida",
  "4858": "Ara\u00e7agi",
  "4859": "Arara",
  "4860": "Araruna",
  "4861": "Areia",
  "4862": "Areia de Bara\u00fanas",
  "4863": "Areial",
  "4864": "Areias (Uira\u00fana)",
  "4865": "Aroeiras",
  "4867": "Assun\u00e7\u00e3o",
  "4868": "Ba\u00eda da Trai\u00e7\u00e3o",
  "4869": "Balan\u00e7os (Cachoeira dos \u00cdndios)",
  "4870": "Bananeiras",
  "4871": "Bara\u00fana",
  "4872": "Barra de Santa Rosa",
  "4873": "Barra de Santana",
  "4874": "Barra de S\u00e3o Miguel",
  "4875": "Barra do Camaratuba (Mataraca)",
  "4876": "Bayeux",
  "12109": "Bebel\u00e2ndia (Santa Rita)",
  "4877": "Bel\u00e9m",
  "4878": "Bel\u00e9m do Brejo do Cruz",
  "4879": "Bernardino Batista",
  "4880": "Boa Ventura",
  "4881": "Boa Vista",
  "4882": "Bom Jesus",
  "4883": "Bom Sucesso",
  "4884": "Bom Sucesso (Soledade)",
  "4885": "Bonito de Santa F\u00e9",
  "4886": "Boqueir\u00e3o",
  "4887": "Borborema",
  "4888": "Brejo do Cruz",
  "4889": "Brejo dos Santos",
  "4890": "Caapor\u00e3",
  "4891": "Cabaceiras",
  "4892": "Cabedelo",
  "4893": "Cachoeira (Guarabira)",
  "4894": "Cachoeira dos \u00cdndios",
  "4895": "Cachoeirinha (Ibiara)",
  "4896": "Cacimba de Areia",
  "4897": "Cacimba de Dentro",
  "4898": "Cacimbas",
  "4899": "Cai\u00e7ara",
  "4900": "Cajazeiras",
  "4901": "Cajazeirinhas",
  "4902": "Caldas Brand\u00e3o",
  "4903": "Camala\u00fa",
  "4904": "Campina Grande",
  "4905": "Campo Alegre (Sousa)",
  "4906": "Campo Grande (Itabaiana)",
  "4907": "Camurupim (Rio Tinto)",
  "4908": "Capim",
  "4909": "Cara\u00fabas",
  "4910": "Cardoso (Concei\u00e7\u00e3o)",
  "4911": "Carrapateira",
  "4912": "Casinha do Homem (Santa Cruz)",
  "4913": "Casserengue",
  "4914": "Catingueira",
  "4915": "Catol\u00e9 (Campina Grande)",
  "4916": "Catol\u00e9 do Rocha",
  "4917": "Caturit\u00e9",
  "4918": "Cepilho (Areia)",
  "4919": "Concei\u00e7\u00e3o",
  "4920": "Condado",
  "4921": "Conde",
  "4922": "Congo",
  "4923": "Coremas",
  "4924": "Coronel Maia (Catol\u00e9 do Rocha)",
  "4925": "Coxixola",
  "4926": "Cruz do Esp\u00edrito Santo",
  "4927": "Cubati",
  "4928": "Cuit\u00e9",
  "4929": "Cuit\u00e9 de Mamanguape",
  "4930": "Cuitegi",
  "4931": "Cupissura (Caapor\u00e3)",
  "4932": "Curral de Cima",
  "4933": "Curral Velho",
  "4934": "Dami\u00e3o",
  "4935": "Desterro",
  "4936": "Diamante",
  "4937": "Dona In\u00eas",
  "4938": "Duas Estradas",
  "4939": "Emas",
  "4940": "Engenheiro \u00c1vidos (Cajazeiras)",
  "4941": "Esperan\u00e7a",
  "4942": "Fagundes",
  "4943": "F\u00e1tima (Cachoeira dos \u00cdndios)",
  "4944": "Fazenda Nova (Uira\u00fana)",
  "4945": "Forte Velho (Santa Rita)",
  "4946": "Frei Martinho",
  "4947": "Gado Bravo",
  "4948": "Galante (Campina Grande)",
  "4949": "Guarabira",
  "4950": "Guarita (Itabaiana)",
  "4951": "Gurinh\u00e9m",
  "4952": "Gurj\u00e3o",
  "4953": "Ibiara",
  "4954": "Igaracy",
  "4955": "Imaculada",
  "4956": "Ing\u00e1",
  "4957": "Itabaiana",
  "4958": "Itajubatiba (Catingueira)",
  "4959": "Itaporanga",
  "4960": "Itapororoca",
  "4961": "Itatuba",
  "4962": "Jacara\u00fa",
  "4963": "Jeric\u00f3",
  "4964": "Jo\u00e3o Pessoa",
  "507725": "Joca Claudino",
  "4965": "Juarez T\u00e1vora",
  "4966": "Juazeirinho",
  "4967": "Junco do Serid\u00f3",
  "4968": "Juripiranga",
  "4969": "Juru",
  "4970": "Lagoa",
  "4971": "Lagoa de Dentro",
  "4972": "Lagoa de Dentro (Campina Grande)",
  "4973": "Lagoa Seca",
  "4974": "Lastro",
  "4975": "Lerol\u00e2ndia (Santa Rita)",
  "4976": "Livramento",
  "4977": "Logradouro",
  "4978": "Lucena",
  "4979": "M\u00e3e D&#39;\u00c1gua",
  "4980": "Maia (Bananeiras)",
  "4981": "Malta",
  "4982": "Mamanguape",
  "4983": "Mana\u00edra",
  "4984": "Marca\u00e7\u00e3o",
  "4985": "Mari",
  "4986": "Mariz\u00f3polis",
  "4987": "Massaranduba",
  "4988": "Mata Limpa (Areia)",
  "4989": "Mata Virgem (Umbuzeiro)",
  "4990": "Mataraca",
  "4991": "Matinhas",
  "4992": "Mato Grosso",
  "4993": "Matur\u00e9ia",
  "4994": "Melo (Cuit\u00e9)",
  "4995": "Mogeiro",
  "4996": "Montadas",
  "4997": "Monte Horebe",
  "4998": "Monteiro",
  "4999": "Montevid\u00e9u (Concei\u00e7\u00e3o)",
  "5000": "Mulungu",
  "5001": "Muqu\u00e9m (Areia)",
  "5002": "Natuba",
  "5003": "Nazar\u00e9 (Pocinhos)",
  "5004": "Nazarezinho",
  "5005": "Nossa Senhora do Livramento (Santa Rita)",
  "5006": "Nova Floresta",
  "5007": "Nova Olinda",
  "5008": "Nova Palmeira",
  "5009": "N\u00facleo N 2 (Sousa)",
  "5010": "N\u00facleo N 3 (Sousa)",
  "5011": "Odil\u00e2ndia (Santa Rita)",
  "5012": "Olho D&#39;\u00c1gua",
  "5013": "Olivedos",
  "5014": "Ouro Velho",
  "5015": "Parari",
  "5016": "Passagem",
  "5017": "Patos",
  "5018": "Paulista",
  "5019": "Pedra Branca",
  "5020": "Pedra Lavrada",
  "5021": "Pedras de Fogo",
  "5022": "Pedro R\u00e9gis",
  "5023": "Pelo Sinal (Mana\u00edra)",
  "5024": "Pereiros (Sousa)",
  "5025": "Pianc\u00f3",
  "5026": "Picu\u00ed",
  "5027": "Pilar",
  "5028": "Pil\u00f5es",
  "5029": "Pil\u00f5ezinhos",
  "5030": "Pindur\u00e3o (Camala\u00fa)",
  "5031": "Pio X (Sum\u00e9)",
  "5032": "Pirau\u00e1 (Natuba)",
  "5033": "Pirpirituba",
  "5034": "Pitanga de Estrada (Mamanguape)",
  "5035": "Pitimbu",
  "5036": "Pocinhos",
  "5037": "Po\u00e7o Dantas",
  "5038": "Po\u00e7o de Jos\u00e9 de Moura",
  "5039": "Pombal",
  "5040": "Porteirinha de Pedra (Campina Grande)",
  "5041": "Prata",
  "5042": "Princesa Isabel",
  "5043": "Puxinan\u00e3",
  "5044": "Queimadas",
  "5045": "Quixab\u00e1",
  "5046": "Quixad\u00e1 (Uira\u00fana)",
  "5047": "Rem\u00edgio",
  "5048": "Riach\u00e3o",
  "4866": "Riach\u00e3o do Bacamarte",
  "5049": "Riach\u00e3o do Po\u00e7o",
  "5050": "Riacho de Santo Ant\u00f4nio",
  "5051": "Riacho dos Cavalos",
  "5052": "Ribeira (Santa Rita)",
  "5053": "Rio Tinto",
  "5054": "Rua Nova (Bel\u00e9m)",
  "5055": "Salema (Rio Tinto)",
  "5056": "Salgadinho",
  "5057": "Salgado de S\u00e3o F\u00e9lix",
  "5058": "Santa Cec\u00edlia",
  "5059": "Santa Cruz",
  "5060": "Santa Gertrudes (Patos)",
  "5061": "Santa Helena",
  "5062": "Santa In\u00eas",
  "5063": "Santa Luzia",
  "5064": "Santa Luzia do Cariri (Serra Branca)",
  "5065": "Santa Maria (S\u00e3o Jo\u00e3o do Tigre)",
  "5066": "Santa Rita",
  "5067": "Santa Rita (Uira\u00fana)",
  "5068": "Santa Teresinha",
  "5069": "Santa Terezinha (Campina Grande)",
  "5070": "Santana de Mangueira",
  "5071": "Santana dos Garrotes",
  "5073": "Santo Andr\u00e9",
  "5075": "S\u00e3o Bentinho",
  "5074": "S\u00e3o Bento",
  "5076": "S\u00e3o Domingos de Pombal",
  "5077": "S\u00e3o Domingos do Cariri",
  "5078": "S\u00e3o Francisco",
  "5079": "S\u00e3o Gon\u00e7alo (Sousa)",
  "5080": "S\u00e3o Jo\u00e3o Bosco (Uira\u00fana)",
  "5081": "S\u00e3o Jo\u00e3o do Cariri",
  "5082": "S\u00e3o Jo\u00e3o do Rio do Peixe",
  "5083": "S\u00e3o Jo\u00e3o do Tigre",
  "5084": "S\u00e3o Jos\u00e9 da Lagoa Tapada",
  "5085": "S\u00e3o Jos\u00e9 da Mata (Campina Grande)",
  "5086": "S\u00e3o Jos\u00e9 de Caiana",
  "5087": "S\u00e3o Jos\u00e9 de Espinharas",
  "5088": "S\u00e3o Jos\u00e9 de Marimbas (Cachoeira dos \u00cdndios)",
  "5089": "S\u00e3o Jos\u00e9 de Piranhas",
  "5090": "S\u00e3o Jos\u00e9 de Princesa",
  "5091": "S\u00e3o Jos\u00e9 do Bonfim",
  "5092": "S\u00e3o Jos\u00e9 do Brejo do Cruz",
  "5093": "S\u00e3o Jos\u00e9 do Sabugi",
  "5094": "S\u00e3o Jos\u00e9 dos Cordeiros",
  "5095": "S\u00e3o Jos\u00e9 dos Ramos",
  "5096": "S\u00e3o Mamede",
  "5097": "S\u00e3o Miguel de Taipu",
  "5098": "S\u00e3o Pedro (Santa Cruz)",`

Order in select, example lasts options:
<img width="897" alt="captura de tela 2017-06-06 as 23 24 12" src="https://user-images.githubusercontent.com/425678/26859603-5049ad70-4b0f-11e7-9131-83f209f890c0.png">

**Comment by dnasir** [comment]
Housekeeping
