### ISSUE TITLE
Default selected item on cascaded selects not working

### ISSUE THREAD

**Issue by PhilHawkridge** [dnasir/jquery-cascading-dropdown#71]
Using three cascaded selects; box 2 values dependent on box 1 selection, box 3 values dependent on box 2 selection.  I want all three to be defaulted to the users previous visit selection from cookies.  Using the 'selected' variable works on box 1, but not on boxes 2 & 3.  I'm guessing on the subsequent boxes it tries to set the selected value before all the cascaded data updates have happened.

Also, you have two variables called 'selected'; one a value on the selectBoxes object, the second a boolean on the return object.  Suggest for clarity rename the first to 'selectedItem' or similar.

**Comment by andreamusico** [comment]
No update? I have the same problem: I have a form and, among other input data, I have two boxes (the second one is dependant of the first box). When I submit the form, I'm trying to repopulate the boxes from $_GET values.  Using the 'selected' variable works on box 1, but not on boxes 2. 
I would like to have some help.

**Comment by LanmanGroup** [comment]
if you try to remove  `self._triggerReady()` from `if(!self._requirementsMet())` selected value on cascade works good.

**Comment by dnasir** [comment]
Fixed in latest.
