### ISSUE TITLE
How to prevent duplicate combinations

### ISSUE THREAD

**Issue by weedkiller** [dnasir/jquery-cascading-dropdown#72]
Hi, thanks for this great control.

for e.g. if we have a Table with cascading drop downs, no two combinations should be repeated or duplicated. So the check usually happens on the OnChangeof the seconddropdown in the cascading dropdown

In cases where I have rows of cascading dropdowns, I often face a requirement where the user should not be allowed to pick the same combination of selections across the rows.

**Comment by dnasir** [comment]
Please show me some sample code for me to work with.

**Comment by weedkiller** [comment]
Hello @dnasir this is a very nice drop down control, I like it a lot 👍 

> Use case:

in two or three cascading drop down use case scenario, user is selecting/picking `Country, State and County`, we need to prevent duplicates in the scenario. 

For e.g. if there are 3 drop downs

`USA->Texas ->Dallas `  Valid
`USA->Texas ->Dallas  ` _Not Valid_, prevent Dallas from list
`USA->Texas ->Austin `  Valid

_90% of the cases are for 2 drop down_, but once in a while, if people are using part picker for manufacturing etc, they have 3 or 4 drop downs and we need to prevent duplicate parts, it would be nice for other developers to simply put an attribute or flag `< AllowDuplicates="False"/>`

```
<select name="cars"  AllowDuplicates="False">
    <option value="volvo">Volvo XC90</option>
    <option value="saab">Saab 95</option>
    <option value="mercedes">Mercedes SLK</option>
    <option value="audi">Audi TT</option>
  </select>
```

**Comment by dnasir** [comment]
@weedkiller Sorry for the late reply. Hectic summer.

I would control the data set provided to each dropdown, so that invalid items are not included where they're not supposed to be. You can share a data source between all relevant dropdowns, and apply the filtering logic inside each individual dropdown.

**Comment by weedkiller** [comment]
@dnasir controlling the dataset would not be an option, because inside a grid, you have many rows of the drop downs, and those drop downs are options are based _on what frontend choices USER picked  in the previous rows_. 
The backend does not know what was picked and you do not want to make multiple round trips.

I gave you the JS code to help.

**Comment by dnasir** [comment]
You can use the `source` property to set up a function that can control the visibility of the duplicate items.

Here's a simple example of how you can achieve that. You will need to figure out how to incorporate it into your code.

http://next.plnkr.co/edit/JFOk6Z9emxKPCpdk?preview

**Comment by weedkiller** [comment]
Hello this does the cascade correctly, but it `does not prevent duplicates selections`

Can you give us an option during config or setup, `preventDuplicates = true;`
