### ISSUE TITLE
Using dynamic example with strings instead of numbers

### ISSUE THREAD

**Issue by keoal** [dnasir/jquery-cascading-dropdown#73]
I am using the dynamic example but with strings instead of numbers for the option values, I can see the values in the drop down and I am able to select them getting a list returned below as expected. However the lists have stopped cascasding correctly and all the objects are returned no matter what the selecton is. is there something extra I need to do to use strings instead of numbers in this example?

**Comment by dnasir** [comment]
Please post sample code for me to work with.
