### ISSUE TITLE
How do you prevent duplicate options being created when options are already made in PHP?

### ISSUE THREAD

**Issue by sneakyvince** [dnasir/jquery-cascading-dropdown#76]
I'm currently using this jQuery plugin for a WordPress project where I have 2 cascading dropdowns:

A static dropdown for selecting a golfclub where it populates the options with a WP_Query of a post type. 

and 

A dynamic dropdown for selecting a golfcourse that is a child page of the golf club (done via Ajax wp_query). After saving the post, this post meta is set and this dropdown is filled with options via php (static)

However after the jQuery cascading dropdown plugin loads on a saved post it will also add the same dropdown options thus making duplicates. It also deselects the previously selected option. 

Is there any way to prevent this jQuery plugin from adding Ajax sourced options if there's already static options present? And can this plugin then also delete the static options once I change the first dropdown?

Thanks in advance

**Comment by sneakyvince** [comment]
Upon further tought I've basically boiled it down to wanting this:

Before I set the source I want to evaluate if a 'golf course' post meta is already set and if so don't pull in the data via Ajax, however if I select a different golf club in the previous dropdown I need it to do an Ajax request.

I haven't found anyway to achieve this so far.

**Comment by dnasir** [comment]
Can you post some sample code? JSFiddle, Plnkr, etc.
