### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by askpt** [dnasir/jquery-cascading-dropdown#79]
Hey,
I'm using your lib and when I install via npm, I got this audit message:

High | Cross-Site Scripting (XSS)
------------ | -------------
Package | jquery
Patched in | >=3.0.0
Dependency of | jquery-cascading-dropdown
Path | jquery-cascading-dropdown > jquery
More info | https://npmjs.com/advisories/328

Probably the fix is just simple as upgrading the jQuery version.

**Comment by askpt** [comment]
@dnasir This library needs to be updated in npm in order to get fixed. Is it possible to do it?

**Comment by dnasir** [comment]
I'll do that once I've closed a few more issues.

**Comment by askpt** [comment]
@dnasir Thanks a lot for your support on this!
